fnc 2.0.0

diff --git a/fnc/libexec/fnc/fnc-deploy-itembase b/fnc/libexec/fnc/fnc-deploy-itembase
--- a/fnc/libexec/fnc/fnc-deploy-itembase
+++ b/fnc/libexec/fnc/fnc-deploy-itembase
@@ -20,28 +20,28 @@ addAddress "ITEMBASE_PROXY" "$ITEMBASE_PROXY"
 echo >&2 "${0##*/}: info: ItemBaseProxy inited."
 
 # OWNERSHIPV4WHITELIST=[$LANDBASE_PROXY,$APOSTLEBASE_PROXY,$ERC721BRIDGE_PROXY,$DRILLBASE_PROXY,$ITEMBASE_PROXY]
-OWNERSHIPV4WHITELIST=[$LANDBASE_PROXY,$APOSTLEBASE_PROXY,$DRILLBASE_PROXY,$ITEMBASE_PROXY]
-OBJECTOWNERSHIPV4_AUTHORITY=$(dapp create src/ObjectOwnershipAuthorityV4.sol:ObjectOwnershipAuthorityV4 $OWNERSHIPV4WHITELIST)
-addAddress "OBJECTOWNERSHIPV4_AUTHORITY" "$OBJECTOWNERSHIPV4_AUTHORITY"
-echo >&2 "${0##*/}: info: ObjectOwnershipAuthorityV4 created."
+# OWNERSHIPV4WHITELIST=[$LANDBASE_PROXY,$APOSTLEBASE_PROXY,$DRILLBASE_PROXY,$ITEMBASE_PROXY]
+# OBJECTOWNERSHIPV4_AUTHORITY=$(dapp create src/ObjectOwnershipAuthorityV4.sol:ObjectOwnershipAuthorityV4 $OWNERSHIPV4WHITELIST)
+# addAddress "OBJECTOWNERSHIPV4_AUTHORITY" "$OBJECTOWNERSHIPV4_AUTHORITY"
+# echo >&2 "${0##*/}: info: ObjectOwnershipAuthorityV4 created."
 
 
-seth send -F $OWNER $OBJECTOWNERSHIP_PROXY "setAuthority(address)" $OBJECTOWNERSHIPV4_AUTHORITY 
-AUTHV4_ADDR=$(seth call $OBJECTOWNERSHIP_PROXY "authority()(address)")
-if test "$AUTHV4_ADDR" != $(seth --to-checksum-address $OBJECTOWNERSHIPV4_AUTHORITY) ; then
-  (echo "migrate ObjectOwnershipAuthorityV4 failed ${auth}"; exit 1;)
-fi
+# seth send -F $OWNER $OBJECTOWNERSHIP_PROXY "setAuthority(address)" $OBJECTOWNERSHIPV4_AUTHORITY 
+# AUTHV4_ADDR=$(seth call $OBJECTOWNERSHIP_PROXY "authority()(address)")
+# if test "$AUTHV4_ADDR" != $(seth --to-checksum-address $OBJECTOWNERSHIPV4_AUTHORITY) ; then
+#   (echo "migrate ObjectOwnershipAuthorityV4 failed ${auth}"; exit 1;)
+# fi
 
-# allowlist=($LANDBASE_PROXY $APOSTLEBASE_PROXY $ERC721BRIDGE_PROXY $DRILLBASE_PROXY $ITEMBASE_PROXY)
-allowlist=($LANDBASE_PROXY $APOSTLEBASE_PROXY $DRILLBASE_PROXY $ITEMBASE_PROXY)
-for allow in "${allowlist[@]}"; do
-  res=$(seth call $OBJECTOWNERSHIPV4_AUTHORITY "whiteList(address)(bool)" $allow)
-  if test "$res" != true; then
-    (echo "migrate OWNERSHIPV4WHITELIST failed ${allow}"; exit 1;)
-  fi
-done
+# # allowlist=($LANDBASE_PROXY $APOSTLEBASE_PROXY $ERC721BRIDGE_PROXY $DRILLBASE_PROXY $ITEMBASE_PROXY)
+# allowlist=($LANDBASE_PROXY $APOSTLEBASE_PROXY $DRILLBASE_PROXY $ITEMBASE_PROXY)
+# for allow in "${allowlist[@]}"; do
+#   res=$(seth call $OBJECTOWNERSHIPV4_AUTHORITY "whiteList(address)(bool)" $allow)
+#   if test "$res" != true; then
+#     (echo "migrate OWNERSHIPV4WHITELIST failed ${allow}"; exit 1;)
+#   fi
+# done
 
-echo >&2 "${0##*/}: info: setAuthority finished."
+# echo >&2 "${0##*/}: info: setAuthority finished."
 
 seth send -F $OWNER $INTERSTELLARENCODERV4 "registerNewObjectClass(address,uint8)" $ITEMBASE_PROXY $(seth --to-hex 5) 
 ITEM_ID=$(seth call $INTERSTELLARENCODERV4 "classAddress2Id(address)(uint8)" $ITEMBASE_PROXY)
