redeploy

diff --git a/fnc/libexec/fnc/fnc-deploy-formula b/fnc/libexec/fnc/fnc-deploy-formula
--- a/fnc/libexec/fnc/fnc-deploy-formula
+++ b/fnc/libexec/fnc/fnc-deploy-formula
@@ -9,14 +9,14 @@ if [ "$FNC_VERBOSE" ]; then set -x; fi
 
 loadAddresses
 
-registry=$(seth --to-bytes32 $(seth --to-hex $(seth --from-ascii "CONTRACT_ERC721_GEGO")))
-seth send -F $OWNER $ISETTINGSREGISTRY "setAddressProperty(bytes32,address)" "$registry" "$TOKEN_GEGO"
+# registry=$(seth --to-bytes32 $(seth --to-hex $(seth --from-ascii "CONTRACT_ERC721_GEGO")))
+# seth send -F $OWNER $ISETTINGSREGISTRY "setAddressProperty(bytes32,address)" "$registry" "$TOKEN_GEGO"
 
-GEGO_ADDR=$(seth call $ISETTINGSREGISTRY "addressOf(bytes32)(address)" "$registry")
-if test "$GEGO_ADDR" != $(seth --to-checksum-address "$TOKEN_GEGO"); then
-  (echo "check register ${registry} failed."; exit 1;)
-fi
-echo >&2 "${0##*/}: info: Gego register finished."
+# GEGO_ADDR=$(seth call $ISETTINGSREGISTRY "addressOf(bytes32)(address)" "$registry")
+# if test "$GEGO_ADDR" != $(seth --to-checksum-address "$TOKEN_GEGO"); then
+#   (echo "check register ${registry} failed."; exit 1;)
+# fi
+# echo >&2 "${0##*/}: info: Gego register finished."
 
 FORMULA=$(dapp create src/Formula.sol:Formula)
 addAddress "FORMULA" "$FORMULA"
