pgl: deploy

diff --git a/fnc/libexec/fnc/fnc-deploy-drillbase b/fnc/libexec/fnc/fnc-deploy-drillbase
--- a/fnc/libexec/fnc/fnc-deploy-drillbase
+++ b/fnc/libexec/fnc/fnc-deploy-drillbase
@@ -50,9 +50,15 @@ if test $(seth call $INTERSTELLARENCODER "classAddress2Id(address)(uint8)" $DRIL
   (echo "check classAddress2Id failed."; exit 1;)
 fi
 
+# ropsten
 if test $(seth call $INTERSTELLARENCODER "ownershipId2Address(uint8)(address)" $(seth --to-hex 1)) != $IOBJECTOWNERSHIP_PROXY; then
   (echo "check ownershipId2Address failed."; exit 1;)
 fi
+
+# crab
+# if test $(seth call $INTERSTELLARENCODER "ownershipId2Address(uint8)(address)" $(seth --to-hex 3)) != $IOBJECTOWNERSHIP_PROXY; then
+#   (echo "check ownershipId2Address failed."; exit 1;)
+# fi
   
 # setting registry
 drill=$(seth --to-bytes32 $(seth --to-hex $(seth --from-ascii "CONTRACT_DRILL_BASE")))
diff --git a/fnc/libexec/fnc/fnc-deploy-formula b/fnc/libexec/fnc/fnc-deploy-formula
--- a/fnc/libexec/fnc/fnc-deploy-formula
+++ b/fnc/libexec/fnc/fnc-deploy-formula
@@ -5,6 +5,13 @@ set -e
 # shellcheck source=lib/common.sh
 . "${0%/*}/../../lib/common.sh"
 
+registry=$(seth --to-bytes32 $(seth --to-hex $(seth --from-ascii "CONTRACT_ERC721_GEGO")))
+seth send -F $OWNER $ISETTINGSREGISTRY "setAddressProperty(bytes32,address)" $registry $TOKEN_GEGO
+if test $(seth call $ISETTINGSREGISTRY "addressOf(bytes32)(address)" $registry) != $TOKEN_GEGO; then
+  (echo "check register ${registry} failed."; exit 1;)
+fi
+echo >&2 "${0##*/}: info: installerEncoder register finished."
+
 FORMULA=$(dapp create src/Formula.sol:Formula)
 addAddress "FORMULA" "$FORMULA"
 echo >&2 "${0##*/}: info: Formula created."
